### ISSUE TITLE
Gamemode Compiling Problems

### ISSUE THREAD

**Issue by soloadv** [NexiusTailer/Nex-AC#132]
Hi. Here am I, with some problems. I'm using the v1.9.49, after I placed the #include <nex-ac> to the filterscripts & gamemode, now after I compile my gamemode, it's going wild with these errors:

- Errors https://pastebin.com/mqZT5E97
- 2nd line (from the gamemode) https://pastebin.com/d0LgDPLw

The line from the gamemode is from another anti-cheat. [ https://pastebin.com/8Z1nnisF ]
Now, how can I fix these?

**Comment by NexiusTailer** [comment]
Well first of all check out what is on these lines in the ac (2084, 2082, 7487 etc) and make some conclusion which functions exactly have different number of arguments so that you will be able to find them in your GM and fix it. Looking at "priority" and "areaid" that figures out in the errors I can assume your Streamer Plugin version is outdated so update it and all other dependencies if there any. Also I recommend you to remove all other anticheats if you don't want to see some other possible compatibility problems in the future.
