### ISSUE TITLE
Question regarding old commit

### ISSUE THREAD

**Issue by Chaprnks** [NexiusTailer/Nex-AC#149]
The other day, I realized that my Nex-AC include was a relic & I needed to update it. I noticed that the #if inclusions for y_hooks was completely removed (and for some time now). I was curious why that was done? I found it to work much more smoother with my current script (as it is completely modulized utilizing y_hooks, even in all the includes).

**Comment by NexiusTailer** [comment]
At that time when I added advanced y_hooks support, I wasn't fully realise its internal structure and many other small nuances with it. As it turned out later, this really had had a lot of problems in opposition to everything that this was intended to solve:
* The first major and one of the crucial problem is that I cannot use y_hooks for those callbacks that need to be hooked in a non-standard way, when I still need to do some final actions on the anticheat side after calling the hook (you can see this in [OnGameModeInit](https://github.com/NexiusTailer/Nex-AC/blob/67c325418546474f9020093ded1d31ea3c3d7129/src/v1.9.52/nex-ac.inc#L3396-L3412), [OnGameModeExit](https://github.com/NexiusTailer/Nex-AC/blob/67c325418546474f9020093ded1d31ea3c3d7129/src/v1.9.52/nex-ac.inc#L3428-L3446), [OnPlayerSpawn](https://github.com/NexiusTailer/Nex-AC/blob/67c325418546474f9020093ded1d31ea3c3d7129/src/v1.9.52/nex-ac.inc#L3789-L3802), [OnPlayerUpdate](https://github.com/NexiusTailer/Nex-AC/blob/67c325418546474f9020093ded1d31ea3c3d7129/src/v1.9.52/nex-ac.inc#L5651-L5661), [OnPlayerWeaponShot](https://github.com/NexiusTailer/Nex-AC/blob/67c325418546474f9020093ded1d31ea3c3d7129/src/v1.9.52/nex-ac.inc#L6888-L6910), [OnPlayerRequestSpawn](https://github.com/NexiusTailer/Nex-AC/blob/67c325418546474f9020093ded1d31ea3c3d7129/src/v1.9.52/nex-ac.inc#L7275-L7289) and [OnUnoccupiedVehicleUpdate](https://github.com/NexiusTailer/Nex-AC/blob/67c325418546474f9020093ded1d31ea3c3d7129/src/v1.9.52/nex-ac.inc#L7851-L7900)). I think you also see this is pretty important there to execute those parts of code only if the ac has full confidence the callbacks was processed with success by returning 1 in all the hooks after it. Regular use of y_hooks will simply ignore this situation, so, only because of this about a third of all the hooked publics aren't able to work correctly with this library.
* The second problem is mostly about code style and good practices using y_hooks. As I investigated after a long time of having its additional support is that you should not return certain values like just 0 or 1 using y_hooks, you should return `Y_HOOKS_CONTINUE_RETURN_1`/`Y_HOOKS_CONTINUE_RETURN_0` (or `Y_HOOKS_BREAK_RETURN_1`/`Y_HOOKS_BREAK_RETURN_0`, if it needs to break the hook chain here). In that case ac should have not only two define checks at the end of some callbacks, but also lots of additional define checks at every place where the public is interrupted by returns during anticheat checks.

Only one problem I've got after its removing - people has started to face a mess with the code order in OnPlayerSpawn: their code like setting player health/interior/smthg else using y_hooks that execute before any ALS hook is reset in the ac ALS hooks, which are called after... I see similar problems in other includes like weapon-config or anything that doesn't use y_hooks as 'must-have dependency' and it only makes me think that the source of the problem lies in the use of y_hooks itself.
