### ISSUE TITLE
Undetected fly(?) hack

### ISSUE THREAD

**Issue by elvianod982** [NexiusTailer/Nex-AC#166]
I am using Nex-AC 1.9.53 and Pawn.RakNet 1.4.1, with all possible Nex-AC cheat codes enabled.

Just now, I had a player who was using some form of fly(?) hack that went undetected by Nex-AC. There was nothing logged to server_log.txt about this.

Video recording: https://streamable.com/y07bmu

I also tracked the player's animations whilst they were using this cheat, if it helps at all:

![image](https://user-images.githubusercontent.com/50199596/86388116-1d39ec00-bc8c-11ea-8d08-c8091f2f3321.png)

Furthermore, in the video you can see the player's ped speed, again, that may also help.

I'm not sure if improvements can be made in this area, and if not, feel free to close this issue out.

**Comment by NexiusTailer** [comment]
Yeah, there are flyhacks with no animation (they just block it) like in this case, and in such cases it should be detected by player's high speed by anti-speedhack onfoot checks. The cheater who uses that flyhack in the video don't doesn't accelerate too fast so that he stay undetected, but if he had it higher, anti-speedhack would detect him. For sure this is not a good situation when flyhacks at such a relatively low speed go unnoticed and unpunished, but there will be no solution to these cases without regular checks of the player’s height (how far he is from the surface), which cannot be done without the use of third-party resource-intensive plugins like ColAndreas.
