### ISSUE TITLE
SAMPCTL Nex-AC languages

### ISSUE THREAD

**Issue by ItsRobinson** [NexiusTailer/Nex-AC#203]
I can't seem to figure out a way to get nex-ac to use the language pack, without moving it in the folder where the include is located. Obviously, I'm using sampctl so you can't edit the dependencies because they just get updated again next time you install/uninstall a dependency. Is this an issue or am I just being stupid?

**Comment by NexiusTailer** [comment]
Yes, seems this is a problem of pawn.json file and the absence of mentioning localization files there. I don't use sampctl, so after changing the file with a new commit, I would like to hear your feedback again if anything changes after that.

**Comment by ItsRobinson** [comment]
> Yes, seems this is a problem of pawn.json file and the absence of mentioning localization files there. I don't use sampctl, so after changing the file with a new commit, I would like to hear your feedback again if anything changes after that.
> 
> UPD: You can try this again now

Sorry for slow response. Nah not working still, think you need to change the pawn.json to:
"include_path": "lang/nex-ac_en.lang/nex-ac_en.lang" as all the lang files are inside their own folders.

**Comment by NexiusTailer** [comment]
Finally I was forced to just download sampctl myself and make the appropriate configs for it in each of my repos, thanks :P
Hope now it will be without any troubles.

As for this:
> RE-UPDATE:
Could you also make adjustments to the DEBUG so that we can disable it like the the NO_SUSPICION_LOGS, atm there's no way to disable the DEBUG lines.

Initially, defines like DEBUG were done rather ill-considered and instead of giving them true/false values and checking for it further down the code, the define simply "exists" and thus activates all the necessary checks. So, the only way to disable it is to simply comment/uncomment it, but since it's enabled by default, you have to make edits in the include itself. I'm not sure if I can do something about this now, for the sake of backward compatibility with previous versions.
