### ISSUE TITLE
knife bug

### ISSUE THREAD

**Issue by nex693** [NexiusTailer/Nex-AC#217]

**Comment by nex693** [comment]
knife bug

**Comment by nex693** [comment]
[18/04/2021 19:03:56] [Nex-AC debug] Dist: 4683.323730, dist set: 25000.000000, speed: 0, pos x, y, z: -2615.964843, 338.775817, 4.336943, old pos x, y, z: 1958.378295, 1343.157226, 15.374600
[18/04/2021 19:03:56] [Nex-AC] ID : 7. Code: 002 (2)
[18/04/2021 19:03:56] [part] quee has left the server (7:2)

She kicks when she cuts her throat

**Comment by NexiusTailer** [comment]
Provide minimal working code example on which this starts to occur

**Comment by nex693** [comment]
I can't provide anti cheat system full of bug. these mistakes did not exist in the past

new bug: when someone kills me it says Fake Kill on me (this happened after new release)

There are new bugs in 1.9.55, please correct.

**Comment by NexiusTailer** [comment]
So you should be interested to solve it itself and provide specific data to be able to understand, test (reproduce) the problem and find out its cause. Otherwise your claims have little effect.

I am no more interested in solving your problems than you are yourself. If you come just complaining about abstract things without any specifics, it won't be fixed 🤷‍♂️.
