### ISSUE TITLE
SetPlayerHealth & SetPlayerInterior

### ISSUE THREAD

**Issue by JocarlosSantts** [NexiusTailer/Nex-AC#228]
The two variables I mentioned in the title when you log back from the server, they are not loaded correctly...

Inside the server it usually happens, but when reloging on the server it is simply unusable.

When the player logs out with a health of 30, when he logs into the server again, the health returns to 100

the player logs out inside X, when it logs back again inside it returns to 0

Please correct.

**Comment by NexiusTailer** [comment]
Share the code witch causes such problem on a blank game so I could reproduce it.

**Comment by JocarlosSantts** [comment]
SetPlayerHealth(playerid, PlayerInfo[playerid][Vida]);
SetPlayerInterior(playerid, PlayerInfo[playerid][Interior);

**Comment by NexiusTailer** [comment]
Everything is fine with this code.

**Comment by JocarlosSantts** [comment]
Note: When the player logs into the server, life 100 good, then he falls from a building his life goes to 50 more or less, then he logs off. His life of 50 is saved... When he logs into the server his life is set to 50, but that doesn't happen it goes back to 100 again.

Same situation the interior, the player logs out in interior 10, when he logs in, he goes back to interior 10, but this does not occur, his interior is set to 0 as well.

**Comment by JocarlosSantts** [comment]
cache_get_value_name_float(0, "Health", PlayerInfo[playerid][Health]);
SetPlayerHealth(playerid, PlayerInfo[playerid][Health]);

cache_get_value_name_int(0, "Interior", PlayerInfo[playerid][Interior]);
SetPlayerInterior(playerid, PlayerInfo[playerid][Interior]);

**Comment by NexiusTailer** [comment]
Well, as I said before, nothing should be wrong with this code. Although you can share working example on a blank gm that you **have tested** (and not just cut out from your gm), also providing the public in which this code executes.

**Comment by JocarlosSantts** [comment]
I've tried using AntiCheatGetHealth(playerid, &Float:health) too and it doesn't work.

**Comment by NexiusTailer** [comment]
Because it's not intended for that

**Comment by JocarlosSantts** [comment]
Got it, I've activated the Ant Cheater again, I'll be testing it again...

**Comment by JocarlosSantts** [comment]
Nexius, can you teach me how to use this ant-cheat, what are these functions for? How should I use them, I don't know how to use this ant-cheat, it's detecting things that it's not supposed to detect.

**Comment by NexiusTailer** [comment]
Just read the whole readme, check and set up OnCheatDetected example from CHANGELOG.md (if you need custom punishments) and set some defines located at the beginning of the anticheat like "AC_USE_AMMUNATIONS" to true/false depending on the fact whether you're using such default game systems on your server or not. I can say in most cases that's enough.

In turn, AntiCheatGet* functions is not intended for constant using wherever possible. Those functions were created for debug purposes first (to have access to the anticheat variables which cannot (and shouldn't) be obtained without such API functions directly, as they static-marked). If you need just actual player's sync data, use default Get/Set SA-MP natives, everything which is needed for the anticheat is already hooked.

As for your problem, again, I need proper information to understand and reproduce it. The fact that you cut out from your gm and provided just two lines of code, didn't even indicate where they were executed - this is is extremely little of use for me, and that's why I requested the code which already can reproduce the problem in a blank gm, so that I've expected that you yourself bother to sketch out the minimum actions for an blank empty script on which you would begin to receive this problem and narrowed the search for causes to specific conditions for its reproduction. At the same time, if you could not get this problem with the required code in an empty script, it would immediately become clear that the problem is somewhere deeper in your gm and these functions don't directly affect and don't cause any troubles. Summing up, you should have at least a little bit of your own interest in giving me comprehensive information, with which it would be clear exactly what your problem is and how to solve it.

**Comment by JocarlosSantts** [comment]
I didn't send the code in a blank GM, because the whole system is in MySQL, and it's embedded in several other database connection systems, I'm going to check again, and I make a video explaining to you what takes place inside the server, I think you would understand better...

**Comment by NexiusTailer** [comment]
I need minimum reproduceable code example at the moment. Any videos will just show what you already described and are unlikely to give additional information about the problem. Try to omit any unimportant code pieces and narrow down the actions you apply from the server at the time of the problem to the minimum. And also information about source of execution your functions is still needed (maybe you just assign health and interiors before the anti-cheat performs its spawn event and resets them for itself after your actions?)

**Comment by JocarlosSantts** [comment]
When the player logs in, I call the interior setting and the interior kind of goes and doesn't go, it sets the interior and returns to 0 again, same thing life, sets the last saved life and then returns to 100

**Comment by NexiusTailer** [comment]
Well, **where** do you call these natives? Is it OnPlayerSpawn in your gm? Or some OnPlayerSpawn hook in one of your gm modules? Or in other include (which can be included before the ac)? Or you do it from OnPlayerStateChange? For which state you check the player then?

**Comment by JocarlosSantts** [comment]
The Player enters the account login details, then presses log in. Then it pulls the CallBack of the player's loading data from the database, then sets the data in the variables and the player's spawn is in SetSpawnInfo(playerid, 0, PlayerInfo[playerid][Skin], PlayerInfo[playerid][Pos] [0], PlayerInfo[playerid][Pos][1], PlayerInfo[playerid][Pos][2], PlayerInfo[playerid][Pos][3], 0, 0, 0, 0, 0, 0 );

**Comment by JocarlosSantts** [comment]
Before this SetSpawnInfo comes the Life and Interior variable

**Comment by NexiusTailer** [comment]
So, health and interior sets before the actual player spawn? (before OnPlayerSpawn has called)

**Comment by JocarlosSantts** [comment]
Here's how the setting is

SetPlayerHealth(playerid, PlayerInfo[playerid][Health]);
SetPlayerInterior(playerid, PlayerInfo[playerid][Interior]);
SetSpawnInfo(playerid, 0, PlayerInfo[playerid][Skin], PlayerInfo[playerid][Pos][0], PlayerInfo[playerid][Pos][1], PlayerInfo[playerid][Pos][2], PlayerInfo[playerid ][Pos][3], 0, 0, 0, 0, 0, 0 );

**Comment by NexiusTailer** [comment]
If OnPlayerSpawn callback sended by player only after you've set him health/armour/interior, these values will be reset by the anticheat due to the bugs in the samp classes system. Just set these data when player is actually spawned (in OnPlayerSpawn or in OnPlayerStateChange with PLAYER_STATE_SPAWNED state, if you want).

**Comment by JocarlosSantts** [comment]
Certain friend, I will test and I'll tell you if it worked.

**Comment by JocarlosSantts** [comment]
Nexius, I did the test here for ANT-AIMBOT and it just isn't detecting in the player Silent detects AIMBOT no.

**Comment by JocarlosSantts** [comment]
It would be good if you also develop ANT-REDUCER

**Comment by JocarlosSantts** [comment]
ant-godmod is not detecting either

**Comment by JocarlosSantts** [comment]
ANT-LAG is also not detecting

**Comment by NexiusTailer** [comment]
> Nexius, I did the test here for ANT-AIMBOT and it just isn't detecting in the player Silent detects AIMBOT no.

Some aimbots (including latest silent aims) just don't have any noticeable issues and the signs by which they could be detected. In other words, they simulate a real shot plausibly enough that something could be done about it from the server side.

> ant-godmod is not detecting either

It's work for bullet godmode only

> ANT-LAG is also not detecting

There is no such anticheat in this include

> It would be good if you also develop ANT-REDUCER

Don't understand what exactly this is about
