### ISSUE TITLE
Long callback execution detected (hang or performance issue)

### ISSUE THREAD

**Issue by kolor4do** [NexiusTailer/Nex-AC#242]
I don't know if this is really a problem, but it bothers to see it in the logs.

```
[debug] Long callback execution detected (hang or performance issue)
[debug] AMX backtrace:
[debug] #0 00042110 in public ac_Timer (playerid=0) at nex-ac.inc:8557
```

```
[debug] Long callback execution detected (hang or performance issue)
[debug] AMX backtrace:
 [debug] #0 00042020 in public ac_Timer (playerid=0) at nex-ac.inc:8548
```

```
[debug] Long callback execution detected (hang or performance issue)
[debug] AMX backtrace:
[debug] #0 0001a66c in public OnPlayerUpdate (playerid=0) at nex-ac.inc:4716
```

**Comment by NexiusTailer** [comment]
In this case it's not a hang, but another false detection of almost useless new crashdetect warning, which in 95% of cases throws such false positives on code which in its opinion is slowly executed (and it may be executed for a long time both because of its quality and external reasons, a weak hardware on the physical server / random momentary lag in performance due to other processes / bottleneck in the algorithm which cannot be optimized significantly anymore). So, there are a bunch or possible reasons in general, but here it's not about real performance issue in the ac.

**Comment by VIRUXE** [comment]
It will depend on the amount of time you're detecting also.

**Comment by NexiusTailer** [comment]
> It will depend on the amount of time you're detecting also.

Ofc, but I think this time period is unlikely to change by most users and most likely it is the default value set by crashdetect
