### ISSUE TITLE
how make anti cheat dont blow up cars?

### ISSUE THREAD

**Issue by phantomboy121** [NexiusTailer/Nex-AC#254]
how make anti cheat dont blow up cars spawned from menu?
when i spawn car with menu when i enter the car vehicel will explode 
this will show in consol: 
[Nex-AC debug] AC veh health: 0.000000, veh health: 1000.000000, veh: 1801, playerid:

**Comment by NexiusTailer** [comment]
You probably have shitty redefine for AddStaticVehicle(Ex)/CreateVehicle somewhere which breaks the hook chain for this function so that anticheat can't properly hook this and control that moment when a vehicle is created.

Check all hook for AddStaticVehicle, AddStaticVehicleEx and CreateVehicle and make sure they done according to ALS Hook Method (not just one redefine) and including after the anticheat.
