### ISSUE TITLE
Suspected cheating after destroying a dynamic pickup

### ISSUE THREAD

**Issue by Walter-Correa** [NexiusTailer/Nex-AC#272]
I create a dynamic type 1 pickup and when the player picks up this pickup it is destroyed.

**The following message appears:**
[Nex-AC debug] Pickupid: 12, dist: 2980.294677, dist set: 2795.555664, acSet[7]: -1, playerid: 0
[Nex-AC] Suspicion on the ID 0. Reason code: 006 (1)

**Comment by NexiusTailer** [comment]
Did you include streamer before the anticheat so it could handle dynamic pickups too?

**Comment by Walter-Correa** [comment]
> Did you include streamer before the anticheat so it could handle dynamic pickups too?

Yes, it is included before #include <nex-ac>

**Comment by Walter-Correa** [comment]
When the player picks up in **OnPlayerPickUpDynamicPickup** I use the code:
DestroyDynamicPickup(pickupid);

**Comment by NexiusTailer** [comment]
Maybe you're using `OnPlayerPickUpDynamicPickup` inside a hook in some module which was included before the anticheat, so, it destroys a pickup before it's checked in validation checks for distance to it (in the ac itself)? This could be also due to y_hooks used on this callback so it will have a higher priority to be called there.

**Comment by Walter-Correa** [comment]
I don't use any YSI include!
These are the includes before the anti cheat include:
```
#include <a_samp>
#include <progress2>
#include <strlib>
#include <foreach>
#include <streamer>
#include <YSF>
#include <sscanf2>
#include <Pawn.RakNet>
#include <nex-ac>
```

**Comment by Walter-Correa** [comment]
> Maybe you're using `OnPlayerPickUpDynamicPickup` inside a hook in some module which was included before the anticheat, so, it destroys a pickup before it's checked in validation checks for distance to it (in the ac itself)? This could be also due to y_hooks used on this callback so it will have a higher priority to be called there, than by normal ALS hooks.

**I tried:**
```
#include <a_samp>
#include <streamer>
#include <nex-ac>
```
**But nothing has changed!**

**Comment by NexiusTailer** [comment]
I think I have found the problem:
Dynamic pickups call both callbacks OnPlayerPickUpDynamicPickup as the first and OnPlayerPickUpPickup after this. For this reason, anticheat need to check if the pickup which has passed in OnPlayerPickUpPickup is not streamer's pickup. Thus, when you have a lot of streamer pickups and pick one of them, it destroys in OnPlayerPickUpDynamicPickup and then, when the deal comes to OnPlayerPickUpPickup, this pickups cannot be identified as a valid dynamic pickup (because it was just destroyed so it's not valid anymore). So, for this reason, every single ac check inside OnPlayerPickUpPickup suggests that it has a deal with a regular non-streamer pickup.

Meanwhile, the default anticheat settings [ignores any kicks for code 006](https://github.com/NexiusTailer/Nex-AC/blob/master/CHANGELOG.md) (it just rejects picking up a pickup which wasn't be picked due to long distance to it, if you return 0 in OnCheatDetected for this code). I think this approach will work in this case too, preventing any other unwanted code from executing in case the distance check fails and code 006 is triggered. This was you still don't allow cheaters to pick up real pickups from a distance and still have no kick for that.

**Comment by Walter-Correa** [comment]
I understood! So it is not possible to fix this?

**Comment by NexiusTailer** [comment]
> I understood! So it is not possible to fix this?

Currently I don't see any easy ways
