### ISSUE TITLE
2nd Passenger of a wagon gets kicked

### ISSUE THREAD

**Issue by rt-2** [NexiusTailer/Nex-AC#31]
The maximum player per vehicle is not adapted for the train wagon (model 570).
I wanted to fix it by myself but I can't understand the functioning of 'ac_MaxPassengers'
Thank you,
rt-2

**Comment by WheneverRide** [comment]
You can use these functions to fix problem by yourself:
```
stock aci_GetMaxPassengers(ac_model) {
	// ac_model values: 0 - 211
	return ac_MaxPassengers[ac_model >>> 3] >>> ((ac_model & 7) << 2) & 0xF;	
}
stock aci_SetMaxPassengers(ac_model, number) { // maximum seat_id in this anticheat is 15
	new index = ac_model >>> 3, shift = ((ac_model & 7) << 2);
	ac_MaxPassengers[index] &= (~(7 << shift)); // reset to 0 some bits we needs
	ac_MaxPassengers[index] |= ((number & 0xF) << shift);
}
```

**Comment by rt-2** [comment]
I'm sorry, I'm not sure to understand, where and how should I use those?

**Comment by NexiusTailer** [comment]
@rt-2 , It's not very difficult. I hope that the screen below will help you:
![Imgur](http://i.imgur.com/NXGkbll.png?1)

As can be seen, the order of numbers (with the maximum values of passenger seats) goes from right to left, and also the upcoming "0x" is not taken into account.

So I'll fix it in the next version (I am thinking of replacing this number by 5), thank you!

**Comment by rt-2** [comment]
I might just be very tired, but are both buses rdy to take more than one passenger? (model 431 & 437).
Thanks a lot to @WheneverRide I confirmed that model 431, 437 also are set to 1 passenger incorrectly...

**Comment by rt-2** [comment]
Also, what is the reason for not using a normal Int 2d table? Memory space?

**Comment by NexiusTailer** [comment]
Buses have a bug: when a player put in it through PutPlayerInVehicle function as passenger, then regardless of the specified seat, he will sit down on the first unoccupied (ie if there are no passengers - this will be 1 seat, even if you specified 3 or 5). That's why it have 1.
Nevertheless, I just rechecked this with several passengers who enter the bus themselves (by pressing enter). It seems that I did not take it into consideration at first sight, and really there were problems with it.
So I understood the problem and it will be completely fixed.

As for the format of numbers: to be honest, I just took it from the fixes include. Fixes also used this style, so it is convenient for me to inform its current developer about the inaccuracies found by users of ac, and thus it makes it simple to update array in the ac or share it with the fixes project.
