### ISSUE TITLE
Anti Invisible needs some improvement

### ISSUE THREAD

**Issue by PhillipM18** [NexiusTailer/Nex-AC#339]

**Comment by NexiusTailer** [comment]
Which exact improvement?

**Comment by NexiusTailer** [comment]
Which way he makes himself invisible in this video?

**Comment by NexiusTailer** [comment]
It doesn't say anything about how it works

**Comment by NexiusTailer** [comment]
> > It doesn't say anything about how it works
> 
> https://streamable.com/iazl8d

It also didn't show in which exact way this works

**Comment by PhillipM18** [comment]
maybe i will send you the file invisible hack?

**Comment by NexiusTailer** [comment]
Sure

**Comment by PhillipM18** [comment]
> Sure

done sir, i already send on your discord

**Comment by NexiusTailer** [comment]
So, it is surfing teleport which sends some random surfing object and cannot be detected by code 021 because it doesn't use any spectate sync, as expected. One of the common names for this cheat is "shadow blade" and it can be detected by [rakcheat](https://github.com/f0Re3t/nex-ac_rakcheat), an extended version of this anticheat. Although it's a bit more resource intensive due to quite meticulous onfoot sync checks, you can use it instead of basic nex-ac.
