### ISSUE TITLE
Keep trailer attached

### ISSUE THREAD

**Issue by PatchwerkQWER** [NexiusTailer/Nex-AC#6]
Hi,

I think anticheat for "Keep trailer attached" should be useful. 

BTW How about compatibility with WeaponConfig by Slice? http://forum.sa-mp.com/showthread.php?t=563387

Cheers @NexiusTailer

**Comment by NexiusTailer** [comment]
Hello,
Thanks for the suggestion! Maybe I add this in future versions)

About weapon-config: this script can be used as a full-fledged anticheat. Unfortunately, I don't agree with the idea of simultaneous use of multiple anticheats..

**Comment by PatchwerkQWER** [comment]
WeaponConfig isn't just about AC. It's about edit weapon damage, own weapons etc... It's really complex and useful include. AC inside is just bonus

**Comment by rt-2** [comment]
So the question is:
I am using weapon-config, it is a good anti-health-hack but also replaces the default vending machine and has other stuff.
Can I use your anti cheat also, what would be your recommendation?
Thank you,
rt-2

**Comment by NexiusTailer** [comment]
@rt-2 , I can't give any guarantees, but if they work properly together, that's great

**Comment by rt-2** [comment]
@NexiusTailer Is there a way to disable anti-health-hacks safely in your AC?

**Comment by NexiusTailer** [comment]
Yes, it is possible. Use "EnableAntiCheat" or "EnableAntiCheatForPlayer" function in your script. However you also may use config file (nex-ac_settings.cfg) to disable something code when the server start.

**Comment by rt-2** [comment]
Ok thank you very much, I didn't realized that we can disable only one anti-cheat with this function.
Thank you,
rt-2

**Comment by NexiusTailer** [comment]
Since samp doesn't have callback functions precise when the trailer is attached and detached from the truck, and moreover, the player can continue to send OnTrailerUpdate even after the actual detaching from the truck (it would be possible to detect something wrong only by checking the quaternions of the trailer and the truck, and how they are located in relation to each other) - this cheat is very problematic to reliably fix from the server side. I think the issue worth closing.
